
package rep.user;

/**
 * 关于erp用户表的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum RepUserOrderByFields { 
 SNO,  SNO_DESC , USERID,  USERID_DESC , BRANDNAME,  BRANDNAME_DESC , BRANDTYPE,  BRANDTYPE_DESC , AREA,  AREA_DESC , ADDRESS,  ADDRESS_DESC , MASTERPRICE,  MASTERPRICE_DESC , WORKNUM,  WORKNUM_DESC , WEEKENDNUM,  WEEKENDNUM_DESC , PHONE,  PHONE_DESC , PASSWORD,  PASSWORD_DESC , PARAM1,  PARAM1_DESC , LNG_NORTH,  LNG_NORTH_DESC , LAT_EAST,  LAT_EAST_DESC , PARAM2,  PARAM2_DESC 
}
